### ISSUE TITLE
Path of Exile .smd to .obj convert doesn't work

### ISSUE THREAD

**Issue by mohnonog** [Tzeentchful/transmute#1]
### Decoding
runtime: out of memory: cannot allocate 1441644544-byte block (4063232 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0x592f3e, 0xd)
        /usr/local/Cellar/go/1.11/libexec/src/runtime/panic.go:608 +0x64
runtime.largeAlloc(0x55edb6b8, 0x440101, 0x860000)
        /usr/local/Cellar/go/1.11/libexec/src/runtime/malloc.go:1021 +0x107
runtime.mallocgc.func1()
        /usr/local/Cellar/go/1.11/libexec/src/runtime/malloc.go:914 +0x39
runtime.systemstack(0x448ee5)
        /usr/local/Cellar/go/1.11/libexec/src/runtime/asm_386.s:396 +0x53
runtime.mstart()
        /usr/local/Cellar/go/1.11/libexec/src/runtime/proc.go:1229

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/Cellar/go/1.11/libexec/src/runtime/asm_386.s:357 fp=0x12c53e28 sp=0x12c53e24 pc=0x448fa0
runtime.mallocgc(0x55edb6b8, 0x566500, 0x6da601, 0x0)
        /usr/local/Cellar/go/1.11/libexec/src/runtime/malloc.go:913 +0x676 fp=0x12c53e7c sp=0x12c53e28 pc=0x409736
runtime.makeslice(0x566500, 0x55edb6b8, 0x55edb6b8, 0x8, 0x550ec0, 0x12c14980)
        /usr/local/Cellar/go/1.11/libexec/src/runtime/slice.go:70 +0x59 fp=0x12c53e90 sp=0x12c53e7c pc=0x436d79
github.com/tzeentchful/transmute/utils.ReadNextBytes(0x12c06490, 0x55edb6b8, 0x91, 0x12c8c000, 0x91)
        /Users/antonio/go/src/github.com/tzeentchful/transmute/utils/utils.go:13 +0x33 fp=0x12c53ec4 sp=0x12c53e90 pc=0x4ba0b3
github.com/tzeentchful/transmute/types.(*SMD).Decode(0x12c3c7e0, 0x12c06490, 0x12c06490)
        /Users/antonio/go/src/github.com/tzeentchful/transmute/types/smd.go:74 +0x3ba fp=0x12c53f9c sp=0x12c53ec4 pc=0x4baa5a
main.main()
        /Users/antonio/go/src/github.com/Tzeentchful/transmute/main.go:29 +0xec fp=0x12c53fd0 sp=0x12c53f9c pc=0x53da8c
runtime.main()
        /usr/local/Cellar/go/1.11/libexec/src/runtime/proc.go:201 +0x1ea fp=0x12c53ff0 sp=0x12c53fd0 pc=0x427a2a
runtime.goexit()
        /usr/local/Cellar/go/1.11/libexec/src/runtime/asm_386.s:1324 +0x1 fp=0x12c53ff4 sp=0x12c53ff0 pc=0x44a7d1

**Comment by RoamingAnt** [comment]
I think you might be trying to convert a compressed model without the decompression code from the latest commit. 
Check if your file starts with the hex `0x43, 0x4D, 0x50` this signals that the file is compressed. You will need to build the latest master branch to get it working if that is the case.
`

**Comment by mohnonog** [comment]
Thank you, model was really compressed, but now i have another question, how can i apply colors to model? What files i need and what i must do?

**Comment by RoamingAnt** [comment]
I assume that your talking about adding textures?
The material data associated with an smd model is under the `.sm`file that references the `.smd` this will define the materials with a link to one or more `.mat` files which will tell you what textures and effects get applied to the model. All these files should be in plain text.
